## Prawdopodobieństwo klasyczne

### Kombinatoryka

Kombinatoryka jest działem matematyki zajmującym się sposobem liczenia struktur przeliczalnych (takich, których elementy można ustawić w ciąg, tzn. "wypisać po kolei"). Kombinatoryka zawdzięcza swój rozwój teorii prawdopodobieństwa, z którą jest silnie związana. Z naszego puntku widzenia kombinatoryka pozwoli nam określać **na ile sposobów da się utworzyć dany wzorzec wybierając elementy ze skończonego zbioru**. Dla przykładu wybierzmy zbiór 20 osób. Z tych 20 osób możemy tworzyć różne "wzorce". Możemy na przykład zapytać ile różnych grup trzyosobowych możemy wybrać albo na ile sposobów da się ustawić wszystkie osoby w kolejkę, tak aby za każdym razem ich kolejność była inna. Pomimo tego, że kombinatoryka jest znacznie szerszym działem matematyki, w naszych zastowaniach będziemy wykorzystywać głównie pytania tego rodzaju. 

#### **1. Permutacja**
Zastanówmy się na ile spsosobów może się zakończyć wyścig 4 zawodników, pod warunkiem, że nie będzie remisów.

In [1]:
from itertools import permutations

for i, p in enumerate(permutations('ABCD', 4)):
    print(f'Option {i+1}:'.ljust(12), '1.{} 2.{} 3.{} 4.{}'.format(*p))

Option 1:    1.A 2.B 3.C 4.D
Option 2:    1.A 2.B 3.D 4.C
Option 3:    1.A 2.C 3.B 4.D
Option 4:    1.A 2.C 3.D 4.B
Option 5:    1.A 2.D 3.B 4.C
Option 6:    1.A 2.D 3.C 4.B
Option 7:    1.B 2.A 3.C 4.D
Option 8:    1.B 2.A 3.D 4.C
Option 9:    1.B 2.C 3.A 4.D
Option 10:   1.B 2.C 3.D 4.A
Option 11:   1.B 2.D 3.A 4.C
Option 12:   1.B 2.D 3.C 4.A
Option 13:   1.C 2.A 3.B 4.D
Option 14:   1.C 2.A 3.D 4.B
Option 15:   1.C 2.B 3.A 4.D
Option 16:   1.C 2.B 3.D 4.A
Option 17:   1.C 2.D 3.A 4.B
Option 18:   1.C 2.D 3.B 4.A
Option 19:   1.D 2.A 3.B 4.C
Option 20:   1.D 2.A 3.C 4.B
Option 21:   1.D 2.B 3.A 4.C
Option 22:   1.D 2.B 3.C 4.A
Option 23:   1.D 2.C 3.A 4.B
Option 24:   1.D 2.C 3.B 4.A


Po wypisaniu wszystkich możliwości, widzimy, że wyścig może zakończyć się na 24 różne sposoby. Inaczej mówiąc, zbiór 4-elementowy ma 24 permutacje. Możemy to zapisać jako $P_4=24$. Liczba wszystkich permutacji to liczba różnych sposobów ustawienia elementów zbioru w kolejności. Spróbujmy otrzymać ogolną postać wyrażenia $P_n$ czyli liczby permumtacji zbioru n-elementowego. 

*Rozumowanie*

Weźmy skończony zbiór składający się z n-elementów ($a_1$, $a_2$, ..., $a_n$). Wyobraźmy sobie, że będziemy tworzyć ciągi z tych elementów. Możemy pomyśleć, że przed stworzeniem ciągu dysponujemy ponumerowanymi pustymi miejscami, w które będziemy wstawiać wyrazy ciągu:
$$\_ \quad \_ \quad \_ \quad \_ \quad \dots \quad \_$$ 
$$1 \quad 2 \quad 3 \quad 4 \quad \dots \quad n$$ 
Na pierwszym miejscu może się znaleźć dowolny z n wyrazów ciągu.
$$a_1 \quad \_ \quad \_ \quad \_ \quad \dots \quad \_$$ 
$$a_2 \quad \_ \quad \_ \quad \_ \quad \dots \quad \_$$ 
$$\dots$$ 
$$a_n \quad \_ \quad \_ \quad \_ \quad \dots \quad \_$$ 

Daje nam to n możliwości. Rozważmy pierwszą z nich. W tej możliwości mamy już zajęte miejsce numer 1 (przez element $a_1$, pozostaje więc n-1 miejsc do obsadzenia. Mamy do do dyspozycji n-1 elementów (wszystkie za wyjątkiem $a_1$), więc tworzy to dodatkowe n-1 możliwości:
$$a_1 \quad a_2 \quad \_ \quad \_ \quad \dots \quad \_$$ 
$$a_1 \quad a_3 \quad \_ \quad \_ \quad \dots \quad \_$$ 
$$\dots$$ 
$$a_1 \quad a_n \quad \_ \quad \_ \quad \dots \quad \_$$ 

Dokladnie tyle samo możliwości daje nam sytuacja, w której element $a_2$ (lub dowolny inny) znajduje się na miejscu numer 1. Zatem chcąc zapełnić dwa pierwsze miejsca mamy $n(n-1)$ różnych możliwości – pierwsze miejsce zapełniamy dowolnym elementem ciągu, drugie zapełniamy dowolnym z n-1 pozostałych elementów. Takie rozumowanie możemy ponowić dla miejsca numer 3, 4, itd.
Ostatecznie widzimy, że liczba różnych permutacji będzie równa:

$$P_n=n(n-1)(n-2)\dots2\cdot1=n!$$


In [2]:
from math import factorial

print('4! = ', factorial(4))

4! =  24


Widzimy, że liczba wszystkich wypisanych permutacji odpowiada wyrażeniu $4!$, czyli jest zgodna z wydedukowanym wzorem ogólnym.

#### **2. Wariacja bez powtórzeń**
Załóżmy, że chcemy stworzyć kod PIN do telefonu wykorzystując jedynie cyfry od 0 do 4. Chcemy, aby w naszym kodzie PIN, żadna cyfra nie powtórzyła się. Ile mamy różnych możliwości do wyboru?

In [3]:
from itertools import permutations

for i, v in enumerate(permutations(''.join(str(d) for d in range(5)), 4)):
    print(f'PIN {i+1}:'.ljust(10), ''.join(v))

PIN 1:     0123
PIN 2:     0124
PIN 3:     0132
PIN 4:     0134
PIN 5:     0142
PIN 6:     0143
PIN 7:     0213
PIN 8:     0214
PIN 9:     0231
PIN 10:    0234
PIN 11:    0241
PIN 12:    0243
PIN 13:    0312
PIN 14:    0314
PIN 15:    0321
PIN 16:    0324
PIN 17:    0341
PIN 18:    0342
PIN 19:    0412
PIN 20:    0413
PIN 21:    0421
PIN 22:    0423
PIN 23:    0431
PIN 24:    0432
PIN 25:    1023
PIN 26:    1024
PIN 27:    1032
PIN 28:    1034
PIN 29:    1042
PIN 30:    1043
PIN 31:    1203
PIN 32:    1204
PIN 33:    1230
PIN 34:    1234
PIN 35:    1240
PIN 36:    1243
PIN 37:    1302
PIN 38:    1304
PIN 39:    1320
PIN 40:    1324
PIN 41:    1340
PIN 42:    1342
PIN 43:    1402
PIN 44:    1403
PIN 45:    1420
PIN 46:    1423
PIN 47:    1430
PIN 48:    1432
PIN 49:    2013
PIN 50:    2014
PIN 51:    2031
PIN 52:    2034
PIN 53:    2041
PIN 54:    2043
PIN 55:    2103
PIN 56:    2104
PIN 57:    2130
PIN 58:    2134
PIN 59:    2140
PIN 60:    2143
PIN 61:    2301
PIN 62:    2304
PIN 63: 

Wypisaliśmy wszystkie 120 sposóbów utworzenia 4 cyfrowego PINU z 5 cyfr, przy założeniu, że żadna cyfra nie może się powtórzyć. Możemy to zapisać jako $V^4_5$. Unikatowe ciągi k-elementowe stworzone ze zbioru n elementów nazywamy **wariacjami bez powtórzeń** i oznaczamy symbolem $V^k_n$. Widzimy, że dla k=n, liczba wariacji bez powtórzeń jest równa liczbie permutacji zbioru n-elementowgo. Spróbujmy otrzymać ogólny wzór na $V^k_n$, posługując się rozumowaniem podobnym do tego, które wykorzystaliśmy przy analizie permutacji.  

*Rozumowanie*

Weźmy zbiór n-elementów. Podobnie jak w przypadku permutacji, będziemy z niego tworzyć ciągi, lecz tym razem o długości k. Przed stworzeniem ciągu mamy zatem k miejsc do obsadzenia.
$$\_ \quad \_ \quad \_ \quad \_ \quad \dots \quad \_$$ 
$$1 \quad 2 \quad 3 \quad 4 \quad \dots \quad k$$ 
Na pierwszym miejscu (dokładnie tak samo jak w permutacji) może się znaleźć dowolny spośród n elementów, na drugim dowolny spośród n-1 elementów i tak dalej. Na ostatnim k-tym miejscu może znaleźć się dowolny spośród pozostałych n-k+1 elementów. Dla każdego miejsca liczba możliwości wygląda następująco
$$n \quad n-1 \quad n-2 \quad n-3 \quad \dots \quad n-k+1$$ 
Możemy zatem utworzyć $n(n-1)(n-2)\dots(n-k+1)$ unikatowych ciągów k elementowych spośród n elementów:

$$V^k_n=n(n-1)(n-2)\dots(n-k+1)=\frac{n(n-1)(n-2)\dots2\cdot1}{(n-k)(n-k-1)\dots2\cdot1}=\frac{n!}{(n-k)!}$$

Dla k=n $V^k_n=\frac{n!}{0!}=\frac{n!}{1}=n!=P_k$, czyli zgodnie ze wcześniejszą obserwacją, dla k=n liczba wariacji bez powtórzeń jest równa liczbie permutacji zbioru n-elementowo.

In [4]:
from math import factorial

print('5! / (5-4)! = ', factorial(5) // factorial(1))

5! / (5-4)! =  120


Widzimy, że liczba wszystkich wypisanych kodów PIN $\frac{5!}{(5-4)!}$ wynosi 120, czyli jest zgodna z wydedukowanym wzorem ogólnym.

#### **3. Kombinacja**
Wybierzmy grupę 6 osób. Każda z osób wita się z pozostałymi osobami poprzez zetknięcie łokci. Zastanówmy się ile zetknięć łokci potrzeba, aby wszyscy przywitali się ze wszystkimi.

In [5]:
from itertools import combinations

for i, c in enumerate(combinations(''.join(str(d) for d in range(1,7)), 2)):
    print(f'Option {i+1}:'.ljust(12), 'p{} >< p{}'.format(*c))

Option 1:    p1 >< p2
Option 2:    p1 >< p3
Option 3:    p1 >< p4
Option 4:    p1 >< p5
Option 5:    p1 >< p6
Option 6:    p2 >< p3
Option 7:    p2 >< p4
Option 8:    p2 >< p5
Option 9:    p2 >< p6
Option 10:   p3 >< p4
Option 11:   p3 >< p5
Option 12:   p3 >< p6
Option 13:   p4 >< p5
Option 14:   p4 >< p6
Option 15:   p5 >< p6


Po wypisaniu wszystkich sposobów, widzimy, że potrzeba było 15 zetknięć. Inaczej mówiąc, mamy 15 kombinacji 2-elementowych ze zbioru 6-elementowego. Możemy to zapisać jako $C^2_6=15$. Kombinacja k-elementowa ze zbioru n-elementowego to unikatowy sposób wyboru k elementów spośród n elementów. W kombinacjach nie interesuje nas kolejność elementów (nie ma znaczenia czy osoba numer 1 wita się z osobą numer 2 czy na odwrót – ważna jest sama "przynależność dwóch osób do danego powitania"). Spróbujmy otrzymać wzór ogólny na $C^k_n$.

*Rozumowanie*

Z poprzednich rozważań wiemy, że spośród n-elementów możemy wybrać $V^k_n$ unikatowych ciągów k-elementowych. Spróbujmy wykorzystać tą wiedzę do otrzymania wzoru na liczbę kombinacji. W liczeniu kombinacji nie interesuje nas jednak kolejność, a jedynie fakt przynaleźności do wybranego podzbioru. Z tego względu oczekujemy, że liczba kombinacji $C^k_n$ powinna być mniejsza od liczby wariacji bez powtórzeń $V^k_n$. 

Aby zbadać relację $V^k_n$ i $C^k_n$ posłużmy się konkretnym przykładem. Weźmy n=6 i k=3. Liczba wariacji bez powtórzeń dla tych wartości wynosi $V^3_6=\frac{6!}{(6-3)!}=\frac{6!}{3!}=120$. Oznacza to, że mamy 120 **unikatowych ciągów** 3-elementowych spośród 6 elementów. Chcemy teraz dowiedzieć się ile mamy **unikatowych podzbiorów** 3-elementowych ze zbioru 6 elementów. Dla każdego 3-elementowego podzbioru, czyli każdej trójki, możemy stworzyć $P_3=6$ unikatowych ciągów. W związku tym mamy następującą relację: $C^3_6 \cdot P_3 = V^3_6$. Widzimy, że aby otrzymać liczbę kombinacji wykrzystując wariacje bez powtórzeń musimy uwzględnić fakt, że każdy podzbiór "występuje" wielokrotnie jako ciąg o tych samych elementach, lecz ustawiony w różnej kolejności. Przykładowo, mając zbiór 6 liter $\{a, b, c, d, e, f\}$, na jeden podzbiór 3 liter, np. $\{a,e,f\}$, przypada dokładnie 6 różnych wariacji bez powtórzeń: $(a, e, f)$, $(a, f, e)$, $(e, a, f)$, $(e, f, a)$, $(f, a, e)$ oraz $(f, e, a)$. W ogólności na każdy podzbiór k-elementowy przypada dokładnie $P_k$ odpowiadających wariacji bez powtórzeń. Wykorzystajmy tę obserwację aby otrzymać wyrażenie ogólne na $C^k_n$:

$$C^k_n=\frac{V^k_n}{P_k}=\frac{\frac{n!}{(n-k)!}}{k!}=\frac{n!}{(n-k)!k!}=\binom{n}{k}$$

Wyrażenie $\binom{n}{k}$ nazywane jest [symbolem Newtona](https://pl.wikipedia.org/wiki/Symbol_Newtona).

In [6]:
from math import factorial

factorial(6) // (factorial(2) * factorial(4))

15

Widzimy, że liczba wszystkich kombinacji równa $\binom{6}{2}=15$ jest zgodna ze wzorem ogólnym.

#### **4. Wariacja z powtórzeniami**
Załóżmy że dysponujemy 5 symbolami (mamy alfabet składający się z 5 znaków). Ile różnych słów, składających się z 3 znaków możemy utworzyć w takiej sytuacji?

In [7]:
from itertools import product

for i, c in enumerate(product('abcde', repeat=3)):
    print(f'Word {i+1}:'.ljust(10), ''.join(c))

Word 1:    aaa
Word 2:    aab
Word 3:    aac
Word 4:    aad
Word 5:    aae
Word 6:    aba
Word 7:    abb
Word 8:    abc
Word 9:    abd
Word 10:   abe
Word 11:   aca
Word 12:   acb
Word 13:   acc
Word 14:   acd
Word 15:   ace
Word 16:   ada
Word 17:   adb
Word 18:   adc
Word 19:   add
Word 20:   ade
Word 21:   aea
Word 22:   aeb
Word 23:   aec
Word 24:   aed
Word 25:   aee
Word 26:   baa
Word 27:   bab
Word 28:   bac
Word 29:   bad
Word 30:   bae
Word 31:   bba
Word 32:   bbb
Word 33:   bbc
Word 34:   bbd
Word 35:   bbe
Word 36:   bca
Word 37:   bcb
Word 38:   bcc
Word 39:   bcd
Word 40:   bce
Word 41:   bda
Word 42:   bdb
Word 43:   bdc
Word 44:   bdd
Word 45:   bde
Word 46:   bea
Word 47:   beb
Word 48:   bec
Word 49:   bed
Word 50:   bee
Word 51:   caa
Word 52:   cab
Word 53:   cac
Word 54:   cad
Word 55:   cae
Word 56:   cba
Word 57:   cbb
Word 58:   cbc
Word 59:   cbd
Word 60:   cbe
Word 61:   cca
Word 62:   ccb
Word 63:   ccc
Word 64:   ccd
Word 65:   cce
Word 66:   cda
Word 67:  

Po wypisaniu wszystkich sposobów, widzimy, że przy użyciu 5 liter oraz długości słowa równej 3 można utworzyć 125 unikatowych słów. W wariacji z powtórzeniami, podobnie jak w wariacji bez powtórzeń, tworzymy ciągi k-elemntowe wybierając spośród n-elementów, lecz umożliwiamy powtarzanie się elementu w ramach ciągu. Wariację z powtórzeniami zapisujemy wykorzystując symbol $W^k_n$, więc w naszym przykładzie $W^3_5=125$. Otrzymanie wyrażenia ogólnego na $W^k_n$ jest bardzo łatwe.

*Rozumowanie*

Skoro nie musimy unikać powtórzeń, na każde z k wolnych miejsc możemy wstawić dowolny spośród n symboli. Równocześnie każde miejsce możemy obsadzić niezależnie od innego, nie musząc przejmować się, że stworzyliśmy "nadmiarową" ilość ciągów. W związku z tym całkowita ilość ciągów wynosi:

$$W^k_n = n\cdot n\cdot \dots \cdot n = n^k$$

In [8]:
print(5 ** 3)

125


### Klasyczna definicja prawdopodobieństwa

W najprostszym ujęciu obliczenie prawdopodobieństwa sprowadza się do zwykłego dzielenia, **w którym liczbę interesujących nas wyników końcowych pewnego doświadczenia losowego dzielimy przez liczbę wszystkich możliwych wyników końcowych**. Doświadczenie losowe, to eksperyment którego wyników nie jesteśmy w stanie przewidzieć. Przykładem może być rzut monetą, losowanie lotto lub rozpad promieniotwórczy. W ogólności, wyniki końcowe mogą mieć różną szansę na realizację, jednak w najprostszym przypadku, każdy z możliwych wyników jest tak samo prawdopodobny. To założenie jest spełnione dla większości gier losowych takich jak karty, kości czy losowania. 

Wprowadźmy pewne oznaczenia posługując się przykładem rzutu symetryczną kością. Podkreślenie symetrii obiektu jest zazwyczaj tożsame z powiedzeniem, że każdy wynik ma równą szansę wystąpienia. **Zdarzeniem elementarnym** będziemy nazywać każdy możliwy wynik doświadczenia losowego. Zbiór wszystkich możliwych zdarzeń elementarnych, nazywany również **przestrzenią zdarzeń**, oznaczany jako $\Omega$. W przypadku rzutu kością $\Omega$ zawiera 6 możliwych wyników doświadczenia $\Omega = \{1, 2, 3, 4, 5, 6\}$. **Zdarzeniem losowym** będziemy nazywali każdy podzbiór $\Omega$. Przykładowe zdarzenia losowe to (i) wyrzucenie parzystej liczby oczek $A_1 = \{2, 4, 6\}$, (ii) wyrzucenie sześciu oczek $A_2 = \{6\}$ lub (iii) wyrzucenie liczby oczek będącej liczbą pierwszą $A_3 = \{2, 3, 5\}$. Prawdopodobieństwem zdarzenia losowego będziemy nazywali stosunek:

$$P(A) = \frac{|A|}{|\Omega|}$$

W powyższym wzorze operator (wyrażenie) $|\cdot|$ oznacza moc zbioru, czyli w przypadku zbiorów skończonych liczbę jego elementów. Dla przykładu, prawdopodobieństwo wyrzucenia parzystej liczby oczek wynosi $\frac{|A_1|}{|\Omega|} = \frac{3}{6} = \frac{1}{2}$. W praktyce oznacza to, że powtarzając rzut kością bardzo wiele razy, w około połowie przypadków wyrzucimy liczbę parzystą (zobacz [prawo wielkich liczb](https://pl.wikipedia.org/wiki/Prawo_wielkich_liczb)). W większości sytuacji, gdy musimy obliczyć prawdopodobieństwo zdarzenia losowego, cała trudność problemu polega na znalezienia liczebności zbiorów $A$ oraz $\Omega$. W takich przypadkach z pomocą przychodzi kombinatoryka. 

## Prawdopodobieństwo w pokerze

Poker jest grą losową, w której gracze stawiają zakłady pienieżne, które zazwyczaj wygrywa gracz z najsilniejszym układem pięciu kart. W pokerze wyróżnia się 10 układów kart, uporządkowanych od najsilniejszego do najsłabszego. Czynnikiem, który określa jak silny jest układ jest prawdopodobieństwo jego wystąpienia. Im trudniej wylosować dany układ, tym jest on silniejszy. Spróbujmy obliczyć i porównać prawdopodobieństwa wystąpienia poszczególnych układów.

### Zbiór zdarzeń elementarnych

W przypadku pokera, zbiór zdarzeń elementarnych będzie składał się z układów złożonych z pięciu różnych kart wybranych spośród pełnej talii 52 kart. Zakładamy, że dzięki dokładnemu tasowaniu kart, każdy zestaw pięciu kart ma takie samo prawdopodobieństwo wystąpienia. Zastanówmy sie ile różnych zestawów pięciu kart możemy stworzyć dysponując pełną talią (w pokerze kolejność kart nie ma znaczenia, jedynie sam fakt ich współwystępowania z innymi kartami). Odpowiedź na to pytanie dostarcza nam kombinacja 5-elementowa ze zbioru 52 elementów, czyli $C^5_{52} = \binom{52}{5}=\frac{52!}{47!5!}=2,598,960$. Jak widzimy, liczba wszystkich możliwości to ponad 2.5 miliona!

In [9]:
from math import factorial

omega = factorial(52) // (factorial(52 - 5) * factorial(5))
print(f'All possible poker hands: {omega:,}')

All possible poker hands: 2,598,960


Poniższy kod umożliwia wielokrotne losowanie zestawu pięciu kart i sprawdzanie, do którego układu przynależy dany zestaw. Wielokrotne powtórzenie doświadczenia losowego polegającego na losowaniu zestawu kart pozwoli na "eksperymentalne" określenie prawdopodobieństwa wystąpienia poszczególnych układów. Zgodnie z prawem wielkich liczb, dla dużej liczby eksperymentów częstotliwość wystąpienia danego układu powinna być bliska prawdopodobieńśtwu wystąpienia tego układu. 

---

*Notka programistyczna*

Klasa `Card` reprezentuje pojedynczą kartę do gry. Aby stworzyć kartę należy podać jej wartość, jako jednoelementowy string (do wyboru wartości od `'2'` do `'9'` oraz dziesiątka `'T'`, walet `'J'`, dama `'Q'`, król `'K'` i as `'A'` oraz kolor, również jako jednoelementowy string (do wyboru kier (hearts $\heartsuit$) `'H'`, trefl (clubs $\clubsuit$) `'C'`, pik (spades $\spadesuit$) `'S'` oraz karo (diamons $\diamondsuit$) `'D'`. Przykładowo `Card(value='T', suit='S')` tworzy dziesiątkę pik. Atrybuty `value` oraz `suit` zwracają odpowiedniki liczbowe danych wartości oraz kolorów dla ułatwienia detekcji układów. Karty posiadają kompaktową reprezentajcę znakową – np. `5D` jest reprezentacją piątki karo.

Klasa `Deck` reprezentuje pełną talię kart do gry. Metoda `sample` zwraca listę pięciu losowych kart.

Funkcje sprawdzające przyjmują jako argument listę pięciu kart i analizując jej skład określają czy dany zestaw stanowi szukany układ.

In [10]:
import random
from collections import Counter

class Card():
    value_dict = {'T': 10, 'J': 11, 'Q': 12, 'K': 13, 'A': 14}
    suit_dict = {'H': 0, 'C': 1, 'S': 2, 'D': 3}
    
    def __init__(self, value, suit):
        self.value = self.value_dict[value] if value in 'TJKQA' else int(value)
        self.suit = self.suit_dict[suit]
        self._str = value + suit 
    
    def __str__(self):
        return self._str

    def __repr__(self):
        return self._str
    
    
class Deck:
    def __init__(self):
        self.deck = [Card(value=v, suit=s) for s in 'HCSD' for v in '23456789TJQKA']
        random.seed(0)
        
    def sample(self):
        return random.sample(self.deck, k=5)

    
STRAIGHTS = tuple({*range(v, v+5)} for v in range(2, 11)) + ({14, 2, 3, 4, 5}, )    
    
def is_straight(sample):
    if set([card.value for card in sample]) in STRAIGHTS: 
        return True
    return False

def is_flush(sample):
    suits = {card.suit for card in sample}
    if len(suits) == 1: 
        return True
    return False

def is_poker(sample):
    if is_flush(sample) and is_straight(sample): 
        return True
    return False
    
def _get_counts(sample):
    counts = Counter([card.value for card in sample]).values()
    return tuple(sorted(counts, reverse=True))    

def is_pair(sample):
    return True if _get_counts(sample) == (2, 1, 1, 1) else False
    
def is_two_pair(sample):
    return True if _get_counts(sample) == (2, 2, 1) else False

def is_three(sample):
    return True if _get_counts(sample) == (3, 1, 1) else False

def is_four(sample):
    return True if _get_counts(sample) == (4, 1) else False

def is_full(sample):
    return True if _get_counts(sample) == (3, 2) else False

### Poker

Poker to nazwa najrzadszego układu w pokerze. Jest to układ łączący strit oraz kolor. Strit to układ w którym pięć kart można ułożyć w kolejości w której wszystkie wartości następują bezpośrednio po sobie (as może być zarówno najniszą kartą – układ A2345, lub najwyższą TJQKA). Kolor to układ, w którym wszystkie pięć kart ma ten sam kolor. Poker to inaczej "strit w kolorze", czyli karty muszą być ułożone po kolei oraz być w jednym kolorze. Przykładem pokera może być układ $\{7\heartsuit, 8\heartsuit, 9\heartsuit, T\heartsuit, J\heartsuit\}$ czyli kiery od siódemki do dziesiątki.

Spróbujmy obliczyć ile jest różnych kombinacji spośród wszystkich 2,598,960 możliwcych, które dają pokera. Poker może wystąpić w jednym z czterech kolorów, co daje nam cztery możliwości. Dla każdego koloru liczba możliwych stritów wynosi dziesięć od najniższego do najwyższego: A2345, 23456, 34567, ..., 9TJQK, TJQKA. Liczba wszystkich układów dającyh pokera wynosi więc 40:

$$|A_{poker}| = \binom{4}{1}\binom{10}{1} = 40$$

Powyższy zapis oznacza że kolor możemy wybrać na 4 sposoby (wybór jednego elementu spośród 4) a strit na 10 sposobów (wybór jednego elementu spośród 10). Szukane prawdopodobieństwo wynosi:

$$P_{poker} = \frac{|A_{poker}|}{|\Omega|} = \frac{40}{2,598,960} \approx 0.0015\%$$

Przeprowadźmy symulację, aby oszacować to prawdopodobieństwo eksperymentalnie.

In [11]:
n = 10_000_000
d = Deck()

n_poker = 0
for _ in range(n):
    if is_poker(d.sample()):
        n_poker += 1
        
freq = 100 * n_poker / n
print(f'Out of {n:,} experiments {n_poker:,} poker hands occured (frequency {freq:0.5f}%)')

Out of 10,000,000 experiments 152 poker hands occured (frequency 0.00152%)


### Kareta

Kareta to układ, w którym cztery spośród pięciu kart mają jednakową wartość. Przykładem karety, może być kareta piątek $\{5\clubsuit, 5\heartsuit, 5\spadesuit, 5\diamondsuit, J\heartsuit\}$ z dodatkowym waletem. Obliczmy, na ile sposobów możemy utworzyć układ, który będzie karetą. 

Kartę, której wartość występuje cztery razy możemy wybrać na 13 sposobów (możemy wybrać dowolną wartość od 2 do asa). Dla każdej wylosowanej czwórki mamy jedno wolne miejsce na piątą kartę. Możemy obsadzić to miejsce każdą z pozostałych w talii kart, co da nam inny układ. Po wyjęciu czterech kart w talii pozostaje 48 kart, więc ilość kombinacji, które dają karetę wynosi $13\cdot 48=624$. Możemy to zapisać przy pomocy kombinacji:

$$|A_{kareta}| = \binom{13}{1}\binom{48}{1} = 13\cdot 48 = 624$$

Szukane prawdopodobieństwo wynosi:

$$P(A_{kareta}) = \frac{|A_{kareta}|}{|\Omega|} = \frac{624}{2,598,960} \approx 0.024\%$$

In [12]:
n = 2_000_000
d = Deck()

n_four = 0
for _ in range(n):
    if is_four(d.sample()):
        n_four += 1
        
freq = 100 * n_four / n
print(f'Out of {n:,} experiments {n_four:,} four-of-a-kind hands occured (frequency {freq:0.5f}%)')

Out of 2,000,000 experiments 502 four-of-a-kind hands occured (frequency 0.02510%)


### Full

Full to układ składający się z trójki i pary (występują trzy karty o tej samej wartości oraz para kart o tej samej wartości). Przykładem fulla, może być układ składający się z trójki szóstek i pary dam $\{6\clubsuit, 6\heartsuit, 6\spadesuit, Q\spadesuit, Q\heartsuit\}$. Obliczmy, na ile sposobów możemy utworzyć fulla. 

Najpierw wybierzmy trójkę kart o tej samej wartości. Wartość możemy wybrać na 13 sposobów (od 2 do asa). Jako, że musimy wykorzystać tylko trzy z czterech kart o wybranej wartości, dla każdej z nich mamy $\binom{4}{3}=4$ kombinacje (wybór trzech kolorów spośród czterech, czyli HCS, HCD, HSD, CSD). Ostatecznie trójkę możemy wybrać na 52 sposóby (13 różnych wartości i dla każdej z nich 4 kombinacje kolorystyczne). Dla każdej dobranej trójki musimy dobrać parę. Wartość pary możemy wybrać na 12 sposobów (odrzucamy wartość, którą zarezerwowaliśmy dla trójki). Dla każdej z wartości musimy wybrać kolory. Ponieważ para składa się z dwóch kart, musimy wybrać 2 spośród 4 kolorów, co daje nam $\binom{4}{2}=6$ kombinacji (HC, HS, HD, CS, CD, SD). Podsumowując, wszystkich możliwości otrzymujemy:

$$|A_{full}| = \binom{13}{1}\binom{4}{3}\binom{12}{1}\binom{4}{2} = 13\cdot 4\cdot 12\cdot 6=3,744$$

Szukane prawdopodobieństwo wynosi:

$$P(A_{full}) = \frac{|A_{full}|}{|\Omega|} = \frac{3,744}{2,598,960} \approx 0.144\%$$

In [13]:
n = 1_000_000
d = Deck()

n_full = 0
for _ in range(n):
    if is_full(d.sample()):
        n_full += 1
        
freq = 100 * n_full / n
print(f'Out of {n:,} experiments {n_full:,} full house hands occured (frequency {freq:0.5f}%)')

Out of 1,000,000 experiments 1,400 full house hands occured (frequency 0.14000%)


### Kolor

Kolor to układ pięciu kart w tym samym kolorze. Możemy mieć na przykład kolor składający się z pików $\{2\spadesuit, 4\spadesuit, 8\spadesuit, Q\spadesuit, J\spadesuit\}$. Obliczmy, na ile sposobów możemy utworzyć kolor. 

Kolor możemy wybrać na cztery sposoby (mamy do wyboru pik, trefl, karo i kier). Po wyborze koloru musimy wybrać 5 wartości kart spośród 13 dostępnych (np. 248QJ, 45QJK, itd.). Na ile sposobów możemy wybrać 5 elementów spośród 13? Odpowiedź na to pytanie dostarcza nam kombinacja 5-elementowa w zbiorze 13 elementów $C^5_{13}=\binom{13}{5}=\frac{13!}{8!5!}=1287$. Możemy więc wybrać $4\cdot 1287$ kombinacji 5 kart w tym samym kolorze. Należy jednak pamiętać, iż jako kolor nie będziemy liczyli pokera (który jest kombinacją w jednym kolorze) stanowiącego osobną kategorię. Od wszystkich kombinacji w kolorze musimy więc odjąć 40 zarezerowanych dla pokera. Ostatecznie mamy:

$$|A_{kolor}| = \binom{4}{1}\binom{13}{5} - 40 = 4\cdot 1287-40=5,108$$

Szukane prawdopodobieństwo wynosi:

$$P(A_{kolor}) = \frac{|A_{kolor}|}{|\Omega|} = \frac{5,108}{2,598,960} \approx 0.197\%$$

In [14]:
n = 1_000_000
d = Deck()

n_flush = 0
for _ in range(n):
    sample = d.sample()
    if is_flush(sample) and not is_poker(sample):
        n_flush += 1
        
freq = 100 * n_flush / n
print(f'Out of {n:,} experiments {n_flush:,} flush hands occured (frequency {freq:0.5f}%)')

Out of 1,000,000 experiments 1,999 flush hands occured (frequency 0.19990%)


### Strit

Kolor to układ pięciu kart występujących bezpośrednio po sobie. As w stricie może być zarówno najniższą jak i najwyższą kartą (np. strit od asa $\{A\diamondsuit, 2\spadesuit, 3\spadesuit, 4\heartsuit, J\clubsuit\}$ oraz strit do asa $\{T\spadesuit, J\spadesuit, Q\spadesuit, K\heartsuit, A\heartsuit\}$). Obliczmy, na ile sposobów możemy utworzyć strit. 

Piątkę wartości występujących bezpśrednio po sobie możemy wybrać na 10 sposobów (A2345, 23456, 34567, ..., 9TJQK, TJQKA). Dla każdej piątki musimy dobrać kolory kart. Każda wartość może wystąpić w innym kolorze niezależnie od pozostałych. Na przykład dla strita od 3 do 7, karta o wartości 3 może być pikim, kierem, treflem lub karo, podobnie karta o wartości 4, itd. Daje nam to $4^5$ różnych zestawów kolorów dla każdej wybranej sekwencji wartości. Tak samo jak w przypadku koloru, musimy pamiętać o odjęciu 40 kombinacji zarezerwowanych dla pokera (poker jest również stritem). Ostatecznie otrzymujemy: 

$$|A_{strit}| = \binom{10}{1}\binom{4}{1}^5 - 40=10,200$$

Szukane prawdopodobieństwo wynosi:

$$P(A_{strit}) = \frac{|A_{strit}|}{|\Omega|} = \frac{10,200}{2,598,960} \approx 0.392\%$$

In [15]:
n = 1_000_000
d = Deck()

n_straight = 0
for _ in range(n):
    sample = d.sample()
    if is_straight(sample) and not is_poker(sample):
        n_straight += 1
        
freq = 100 * n_straight / n
print(f'Out of {n:,} experiments {n_straight:,} straight hands occured (frequency {freq:0.5f}%)')

Out of 1,000,000 experiments 3,985 straight hands occured (frequency 0.39850%)


Więcej informacji na temat prawdopodobieństwa w pokerze można przeczytać w [świetnym artykule na angielskiej Wikipedii](https://en.wikipedia.org/wiki/Poker_probability). Zauważmy również, że aby otrzymać precyzyjne przybliżenie prawdopodobieństwa dla zdarzeń bardzo rzadkich (np. wystąpienie pokera) musieliśmy przeprowadzić więcej symulacji niż dla zdarzeń występujących relatywnie często. Gdybyśmy chcieli oszacować prawdopodobieństwo pokera przeprowadzając jedynie 100 tysięcy symulacji, jest możliwe, że poker nie pojawiłby się ani razu (wówczas szacowane $\hat{P}(A_{poker}) = 0$. 